# Generated by Django 2.0.2 on 2018-02-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Positions',
            new_name='Position',
        ),
    ]
