# Generated by Django 2.0.2 on 2018-02-04 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0004_document_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='redaction',
        ),
        migrations.RemoveField(
            model_name='redaction',
            name='document',
        ),
    ]
