# Generated by Django 2.0.2 on 2018-02-05 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0005_auto_20180204_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='redaction',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='foia.Redaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redaction',
            name='document',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='foia.Document'),
            preserve_default=False,
        ),
    ]
