# Generated by Django 2.0.2 on 2018-02-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0006_auto_20180205_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='redaction',
            name='clue',
            field=models.CharField(default='tasty clue', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
