# Generated by Django 2.0.2 on 2018-02-05 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0007_redaction_clue'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='background_color',
            field=models.CharField(default='black', help_text='The color of the redaction. Generally, black or white.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='font',
            field=models.CharField(default='', help_text='The font that best matches the document', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='text_color',
            field=models.CharField(default='white', help_text='Text color to match the redaction.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(help_text='Discribe the document, this will be in the alt text'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(help_text='Upload FOIA image', unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(help_text="Unique title that will appear in the page title. Don't give away exactly what it is.", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(help_text='The person or institution that requested or published the FOIA', max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_url',
            field=models.CharField(help_text='Link to the source of the FOIA', max_length=200),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='clue',
            field=models.CharField(help_text='The prompt that will help visitors guess what this redaction is.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='document',
            field=models.ForeignKey(help_text='The document this redaction belongs to', on_delete=django.db.models.deletion.CASCADE, to='foia.Document'),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='foia_exemption',
            field=models.CharField(help_text='For fun if you have it handy', max_length=200),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='redaction_id',
            field=models.CharField(help_text='name of this redaction', max_length=200, unique=True),
        ),
    ]
